---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-utils-dataway
  name: dataway
  namespace: utils
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-utils-dataway
  template:
    metadata:
      labels:
        app: deployment-utils-dataway
      annotations:
        datakit/logs: |
          [{"disable": true}]
    spec:
      containers:
      - image: pubrepo.jiagouyun.com/dataflux/dataway:1.2.10
        imagePullPolicy: IfNotPresent
        name: dataway
        ports:
        - containerPort: 9528
          name: 9528tcp01
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/cloudcare/dataflux/dataway/dataway.yaml
          name: dataway-config
          subPath: config.yaml
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 256
          name: dataway-config
          optional: false
        name: dataway-config

---

apiVersion: v1
kind: Service
metadata:
  name: dataway
  namespace: utils
spec:
  ports:
  - name: 9528tcp02
    port: 9528
    protocol: TCP
    targetPort: 9528
    nodePort: 30928
  selector:
    app: deployment-utils-dataway
  type: NodePort
