variables:
  REPOSITORY: "dataflux-doc"
  PROJECT: "dataflux-doc"

stages:
  - deploy

buildTesting:
  stage: deploy
  only:
    - dev
  script:
    - docker build -t $REPOSITORY:testing .
    - docker tag $REPOSITORY:testing registry.jiagouyun.com/cloudcare-front/$REPOSITORY:testing
    - docker push registry.jiagouyun.com/cloudcare-front/$REPOSITORY:testing
  tags:
    - cloudcare

