variables:
  REPOSITORY: "dataflux-doc"
  PROJECT: "dataflux-doc"

stages:
  - deploy

buildTesting:
  stage: deploy
  only:
    - dev
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 
      -t registry.jiagouyun.com/cloudcare-front/$REPOSITORY:testing . --push
  tags:
    - cloudcare-multiarch 

