variables:
  REPOSITORY: "dataflux-doc"
  PROJECT: "dataflux-doc"

stages:
  - deploy

buildTesting:
  stage: deploy
  only:
    - dev
  script:
    - docker build --build-arg release_env="peprod" -t $REPOSITORY:testing .
    - docker tag $REPOSITORY:testing registry.jiagouyun.com/cloudcare-front/$REPOSITORY:testing
    - docker push registry.jiagouyun.com/cloudcare-front/$REPOSITORY:testing

    - curl -sS -X POST -H "Authorization:Bearer ${PREPROD_RANCHER_TOKEN}"  ${RANCHER_API_BASE_URL}/v3/project/${PREPROD_PROJECT_ID}/workloads/deployment:${PREPROD_WORKLOAD}?action=redeploy
  tags:
    - cloudcare-multiarch

buildMain:
  stage: deploy
  only:
    - main
  script:
    - docker build --build-arg release_env="saas_production" -t $REPOSITORY:prod .
    - docker tag $REPOSITORY:prod registry.jiagouyun.com/cloudcare-front/$REPOSITORY:prod
    - docker push registry.jiagouyun.com/cloudcare-front/$REPOSITORY:prod
    
    - curl -sS -X POST -H "Authorization:Bearer ${PROD_RANCHER_TOKEN}"  ${RANCHER_API_BASE_URL}/v3/project/${PROD_PROJECT_ID}/workloads/deployment:${PROD_WORKLOAD}?action=redeploy
  tags:
    - cloudcare-multiarch

buildBasis:
  stage: deploy
  only:
    - /basis-\d+/
  script:
    - docker buildx build --platform linux/arm64,linux/amd64
      -t registry.jiagouyun.com/basis/mkdocs:1.0
      -f Dockerfile.basis .
      --push
  tags:
    - cloudcare-multiarch
