variables:
  REPOSITORY: "dataflux-doc"
  PROJECT: "dataflux-doc"

stages:
  - deploy

buildTesting:
  stage: deploy
  only:
    - dev
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 
      -t registry.jiagouyun.com/cloudcare-front/$REPOSITORY:testing . --push
    - curl -sS -X POST -H "Authorization:Bearer ${PREPROD_RANCHER_TOKEN}"  ${RANCHER_API_BASE_URL}/v3/project/${PREPROD_PROJECT_ID}/workloads/deployment:${PREPROD_WORKLOAD}?action=redeploy
  tags:
    - cloudcare-multiarch

buildPreprod:
  stage: deploy
  only:
    - /^pre-(\d-?)+/
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 
      -t registry.jiagouyun.com/cloudcare-front/$REPOSITORY:$CI_COMMIT_REF_NAME . --push
  tags:
    - cloudcare-multiarch

buildBasis:
  stage: deploy
  only:
    - /^basis-\d+/
  script:
    - docker buildx build --platform linux/arm64,linux/amd64
      -t registry.jiagouyun.com/basis/mkdocs:2.0
      -f Dockerfile.basis .
      --push
  tags:
    - cloudcare-multiarch


buildBasis:
  stage: deploy
  only:
    - /^insiders-basis-\d+/
  script:
    - docker buildx build --platform linux/arm64,linux/amd64
      -t registry.jiagouyun.com/basis/mkdocs-material-insiders:4.18.2
      --build-arg GH_TOKEN="${GH_TOKEN}"
      -f Dockerfile.insiders.basis .
      --push
  tags:
    - cloudcare-multiarch

