variables:
  REPOSITORY: "dataflux-doc"
  PROJECT: "dataflux-doc"

stages:
  - deploy

buildTesting:
  stage: deploy
  only:
    - dev
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 
      -t registry.jiagouyun.com/cloudcare-front/$REPOSITORY:testing . --push
    - curl -sS -X POST -H "Authorization:Bearer ${PREPROD_RANCHER_TOKEN}"  ${RANCHER_API_BASE_URL}/v3/project/${PREPROD_PROJECT_ID}/workloads/deployment:${PREPROD_WORKLOAD}?action=redeploy
  tags:
    - cloudcare-multiarch

