FROM python:3.7.7

RUN pip install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple

WORKDIR /tmp
COPY ./requirements.txt /tmp/requirements.txt

RUN pip install  -i https://mirrors.aliyun.com/pypi/simple -r requirements.txt
