site_name: 观测云文档

theme:
  palette:
    primary: white
  name: material
  custom_dir: overrides/
  favicon: favicon.ico
  logo: logo.png
  language: zh
  features:
    - navigation.instant
    - search.suggest
    - toc.follow
    - content.tabs.link

markdown_extensions:
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: True
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

copyright: '&copy; 2013-2022 上海驻云信息科技有限公司 沪公网安备 31011502010862号 | 沪ICP备 13034243号-30'

extra:
  generator: false
  homepage: https://docs.guance.com

plugins:
  - awesome-pages
  - section-index
  - git-authors
  - git-revision-date-localized:
      type: custom
      custom_format: '%Y-%m-%d'
      enable_creation_date: true
      fallback_to_build_date: true
  - search:
      separator: '[\s\u200b\-]'

extra_css:
  - stylesheets/extra.css
